version: '3.8'

services:
  app:
    build: .
    ports:
      - "80:8080"
    environment:
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_DATABASE=${DB_DATABASE}
      - DB_HOST=${DB_HOST}
      - NODE_ENV=development
    volumes:
      - ".:/app"
    networks:
      - pgnodeapp
    depends_on:
      - db
    command: sh -c './wait-for db:5432 -- npm run build-start'


  db:
    image: postgres:12-alpine
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_DATABASE}
    volumes:
      - type: volume
        source: postgres-db
        target: /var/lib/postgresql/data
    networks:
      - pgnodeapp

volumes:
  postgres-db:

networks:
  pgnodeapp:
    driver: bridge
